version: '3.5'

name: ai_rehab_backend

networks:
  default:
    name: ai_rehab_network

volumes:
  poe_db_data:
  frontend_web_build:
    external: true

services:
  poe_db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
      - MSSQL_LCID=1033
      - TZ=Etc/UTC+1
    ports:
      - 1433:1433
    restart: "no"
    volumes:
      - poe_db_data:/var/opt/mssql
      - ./init:/docker-entrypoint-initdb.d
      - ../datamodel/:/scripts
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr &

      until /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '${DB_PASSWORD}' -Q 'SELECT 1' &> /dev/null; 
      do >&2 sleep 5;
      done;
      
      echo 'Database is ready, running .sql scripts';
      /opt/mssql-tools/bin/sqlcmd -S poe_db -U sa -P '${DB_PASSWORD}' -d master -i docker-entrypoint-initdb.d/init.sql;
      /opt/mssql-tools/bin/sqlcmd -l 5 -S poe_db -U sa -P '${DB_PASSWORD}' -d master -i /scripts/schema.sql;
      echo 'Init scripts done';

      sleep infinity;"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 3s
    container_name: poe_db
  poe_server:
    build: .
    environment:
      - TZ=Etc/UTC+1
    depends_on:
      poe_db:
        condition: service_healthy
    links:
      - poe_db
    volumes:
      - ./:/usr/src/app
      - ./uploads/:/usr/src/app/uploads
      - ./logs/:/usr/src/app/logs
      - /usr/src/app/node_modules
      - ../datamodel/:/usr/src/datamodel:ro
      - frontend_web_build:/usr/src/web:ro 
    command: "npm run node:start"
    ports:
      - 8080:8080
    container_name: poe_server